
sudo: false
language: python
cache: pip
python:
  - 2.7
  - 3.5
  - 3.6
env:
  TOXENV=py

# matrix:
#   include:
#     - python: 3.6
#       env: TOXENV=docs
#     - python: 3.6
#       env: TOXENV=fix-lint
#     - os: osx
#       language: generic

before_install:
 - pyenv versions

install:
  - pip install -U six
  - pip install --pre -U tox

script:
  - tox

after_success:
- if [[ $TOXENV == "py" ]]; then tox -e coverage,codecov; fi
